### ISSUE TITLE
Plugin refuses to run on forks of WordPress

### ISSUE THREAD

**Issue by kvibber** [dartiss/shareopenly#23]
I converted a site that was using this plugin to ClassicPress and got this message:

![Share Openly Plugin Refuses to Run On ClassicPress](https://github.com/user-attachments/assets/d79bba54-d8f5-4fcb-86e1-26591420ddc4)

> ShareOpenly has been deactivated
> Reason:
>    A fork of WordPress was detected.

It looks like the problem here is the function shareopenly_fork_check(), which seems to be actively looking for known forks of WordPress and refusing to run on them.

https://github.com/dartiss/shareopenly/blob/main/inc/shared.php#L77

This seems counter to the spirit of something called "ShareOpenly."

If there are known incompatibilities, those should be noted in the README or other plugin documentation. Otherwise, the plugin should just try to run without going to the extra effort of looking for ClassicPress and CalmPress. There's no need to actively block the software.

**Comment by dartiss** [comment]
The plugin has been written for WordPress, and isn't supported on any forks, hence why the code is in place. 

I don't mention incompatibilities in the README for the simple reason that I neither test nor provide support to forks to be able to add this information.

Can I ask which WordPress fork you were using?

**Comment by kvibber** [comment]
There's a big difference between just not testing on other forks, and putting in extra effort to actively *block* them. This seems more like writing a program for Debian and having it actively check for Ubuntu or Mint and refusing to run on them. Or writing a browser extension for Chrome and refusing to let it run on Vivaldi.

I'm not asking you to troubleshoot problems that might be caused by running on ClassicPress. Just stop blocking access to running it on related platforms. I mean, I could remove the function from my copy of the plugin, but that seems kind of ridiculous.

**Comment by dartiss** [comment]
No effort. I wrote the script years ago and the same one is present in all my plugins. It's a lot clearer than my trying to debug my code on a fork, without realising it, before knowing what it is and then having to explain it. This is straight-forward and to the point.

Meanwhile, I've updated the README FAQ to make it clear this is the case.
